### ISSUE TITLE
MBON Pole to Pole site list added

### ISSUE THREAD

**Issue by eqmh** [marinebon/p2p#1]
Hello Ben,

I just uploaded a csv with lat/lons of P2P sites. I would like to show these on the [home page map](https://marinebon.github.io/p2p/index.html) and have them being interactive with the features we talked about on these [notes](https://docs.google.com/document/d/1fyPthk8RWni_O8HNSIu4JjxjLnL9nJratykljqE-Zhk/edit#heading=h.3hcjwr91xybn). There are more detailed notes on app functionalities in these [other notes](https://docs.google.com/document/d/1Sfihy1p90B3xOsoXpXFUBj_90nPITNI6p-hFTWFGiqk/edit#heading=h.c1yxozccyl9h) about how we can display temperature logger data and other things like data sheet conversion to CSV using Google Vision API for OCR, and other stuff.

Let me know if you prefer a different format.
Cheers,
Enrique

**Comment by 7yl4r** [comment]
Similar older discussion about the infographics [here](https://github.com/marinebon/info-fk/issues/34).

Using leaflet with this csv shouldn't be very different.

**Comment by eqmh** [comment]
I am trying to add markers on the map using:
```R
addMarkers(
    lng = -64.8830, 
    lat = -42.8000, 
    popup = ~as.character(mag), 
    label = ~as.character(mag)
)
```
I'm getting this error:

>Error in getMapData(map) : argument "map" is missing, with no default
>Calls: <Anonymous> ... eval -> addPolygons -> derivePolygons -> getMapData

Is this familiar?

**Comment by 7yl4r** [comment]
I had no luck finding anything related. All the examples I see from [leaflet's docs on markers](http://rstudio.github.io/leaflet/markers.html) pass in a dataframe using `R`'s pipe operator (`%>%`). My guess would be that leaflet needs to do some initialization first? Maybe add a `leaflet()` above that?

Something you could do to help us debug would be to push this code into github on a branch or fork (your choice but branch will be easier I think). Good info [here](http://rogerdudler.github.io/git-guide/) but the gist would be:

```bash
# create branch named p2pmap:
git branch p2pmap  

# switch over to that branch on your local
git checkout p2pmap

# add, commit, push on the p2pmap branch
git add file.txt  
git commit -m "attempt addMarkers; getMapData error"
git push origin p2pmap
```

use `git checkout` to switch back to the `master` branch when you are ready.

**Comment by bbest** [comment]
Hey @eqmh,

So I added the site markers to the homepage map:

![image](https://user-images.githubusercontent.com/2837257/47739880-a4bb9600-dc33-11e8-8635-bb8ac85e3932.png)

Here's a few things worthy of note:

- @7yl4r pointed me to the CSV in [MBON Pole to Pole sites list · marinebon/p2p@d94b1df](https://github.com/marinebon/p2p/commit/d94b1dfe98a5c4b7fb3016ec122120759e2f15c7) which got wiped out during the website build process. I updated the repository's [README.md](https://github.com/marinebon/p2p/blob/master/README.md) under the **Building Website** section with more on the what/how/why, especially:
  - **WARNING**: Do _**NOT**_ place any content in the **`docs/`** since it gets wiped clean before rebuilding the website in its place
  - So `docs/MBON_Pole-to-Pole_sites.csv` should be outside `docs/`, like now in `data/sites.csv`
- Here's good reference on how to add markers and popups/labels to a leaflet map in R:
  * [Leaflet for R - Markers](https://rstudio.github.io/leaflet/markers.html)
  * [Leaflet for R - Popups and Labels](https://rstudio.github.io/leaflet/popups.html)
- Here's the implementation diffs for `index.Rmd`:
  - [`addMarkers()`](https://github.com/marinebon/p2p/commit/255f875003d3f72dc236e9f111448ab9e71aa8ba#diff-f06390acc60c07aadad857caace0f767)
  - [`fitBounds()`](https://github.com/marinebon/p2p/commit/59ab3f8725fc5560c37c903491b797d45bdbb3e8#diff-f06390acc60c07aadad857caace0f767)

**Comment by eqmh** [comment]
Thanks, @7yl4r !

I suppose that any changes made to sites.csv will be shown of the map makers, right? I will change the site names on this file.

**Comment by bbest** [comment]
Hey @eqmh,

Yes, you can update the `name` values in `data/sites.csv`, then knit `index.Rmd`, git commit & push.

Cheers, @bbest

**Comment by eqmh** [comment]
Sorry, @bbest, I just realized that you made these changes. Thanks to you!
Cheers,
@eqmh
